# For more details, read this: https://coolify.io/docs/github-actions
name: Build and Deploy Roblox Experience Notifications Development
on:
  push:
    branches: ["development"]

jobs:
  amd64:
    runs-on: ubuntu-latest
    environment: Development
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      # Login to docker registry
      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.REPOSITORY_PASSWORD }}

      # Build image and push to registry
      - name: Build image and push to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest

      # Deploy to Coolify
      - name: Deploy to Coolify
        run: |
          curl --request GET '${{ secrets.COOLIFY_URL }}/api/v1/deploy?uuid=${{ secrets.COOLIFY_APP_UUID }}&force=false' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}' --silent --show-error